services:
  - mongodb

language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 8.1

matrix:
  fast_finish: true

before_install:
  - echo "extension =  mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-add travis.php.ini
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - composer phpcs
  - bin/test
